name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: ['5.40', '5.42']
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v5
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          install-modules-with: cpm
          install-modules-args: --with-test --with-develop
      - run: prove -l -It/lib -r t
      - run: make lint
